// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleOfficeScheduler.Data;

#nullable disable

namespace SimpleOfficeScheduler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221074701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("SimpleOfficeScheduler.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocalAccount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SimpleOfficeScheduler.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SimpleOfficeScheduler.Models.EventOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GraphEventId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.HasIndex("EventId", "StartTime");

                    b.ToTable("EventOccurrences");
                });

            modelBuilder.Entity("SimpleOfficeScheduler.Models.EventSignup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventOccurrenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SignedUpAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EventOccurrenceId", "UserId")
                        .IsUnique();

                    b.ToTable("EventSignups");
                });

            modelBuilder.Entity("SimpleOfficeScheduler.Models.Event", b =>
                {
                    b.HasOne("SimpleOfficeScheduler.Models.AppUser", "Owner")
                        .WithMany("OwnedEvents")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SimpleOfficeScheduler.Models.RecurrencePattern", "Recurrence", b1 =>
                        {
                            b1.Property<int>("EventId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("DaysOfWeek")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Recurrence_DaysOfWeek");

                            b1.Property<int>("Interval")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Recurrence_Interval");

                            b1.Property<int?>("MaxOccurrences")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Recurrence_MaxOccurrences");

                            b1.Property<DateTime?>("RecurrenceEndDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("Recurrence_EndDate");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Recurrence_Type");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("Owner");

                    b.Navigation("Recurrence");
                });

            modelBuilder.Entity("SimpleOfficeScheduler.Models.EventOccurrence", b =>
                {
                    b.HasOne("SimpleOfficeScheduler.Models.Event", "Event")
                        .WithMany("Occurrences")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SimpleOfficeScheduler.Models.EventSignup", b =>
                {
                    b.HasOne("SimpleOfficeScheduler.Models.EventOccurrence", "Occurrence")
                        .WithMany("Signups")
                        .HasForeignKey("EventOccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleOfficeScheduler.Models.AppUser", "User")
                        .WithMany("Signups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occurrence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimpleOfficeScheduler.Models.AppUser", b =>
                {
                    b.Navigation("OwnedEvents");

                    b.Navigation("Signups");
                });

            modelBuilder.Entity("SimpleOfficeScheduler.Models.Event", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("SimpleOfficeScheduler.Models.EventOccurrence", b =>
                {
                    b.Navigation("Signups");
                });
#pragma warning restore 612, 618
        }
    }
}
